import type { Metadata } from "next";
import "./globals.css";
import { ThemeProviders } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Khatri College | Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ThemeProviders>
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
